### ISSUE TITLE
Price option -fdr

### ISSUE THREAD

**Issue by fredericQC** [erhard-lab/gedi#11]
Dear Florian,
I tried `-fdr 0.01` instead of the default `-fdr 0.1` and expected to get less ORFs with the 0.01 FDR and I indeed got less ORFs detected. But some of the ORFs detected with `-fdr 0.01` where not detected with `-fdr 0.1`. Does the FDR, in this case, affect the model?
Thank you!
Frederic

**Comment by florianerhard** [comment]
Dear Frederic,
this is indeed strange and unexpected behavior... about how many ORFs are we talking about? I guess you did a full restart (so not just deleting the prefix.tsv file, but using a new prefix)?

One potential reason is that in one of your runs, the codon model did not fully converge (or converge to a slightly different parameterization). Then some ORFs that are just above or below some cutoffs may or may not end up being considered... 

The FDR calculation is one of the last steps, and comes down to applying Benjamini Hochberg to all p values that came out of the ORF inference (which are the ones in the prefix.tsv file).

So the FDR does not affect the model, but two different runs might produce two slightly different models.

Best,Florian
