### ISSUE TITLE
Why is readcount not an integer?

### ISSUE THREAD

**Issue by ValeriaFam** [erhard-lab/gedi#12]
Hello,

I would like to use GRAND-SLAM in one of my projects and I am trying it now on the mESC data from the GRAND-SLAM paper. 
It all went right so I obtained the .tsv file but I was wondering why is readcount not an integer? Is it normalize? If the answer is yes, on what?

Thank you in advance

**Comment by florianerhard** [comment]
Dear ValeriaFam,
multimapping reads are counted as fractions (i.e. if there are two mapping locations, both are counted as 0.5). Counts are *not* normalized.
Florian
