### ISSUE TITLE
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceEstimateModel

### ISSUE THREAD

**Issue by alhigdon** [erhard-lab/gedi#14]
Hi Florian, 

I'm trying to run PRICE on a single bam file and am getting the error message I pasted below. The bam file was generated using STAR with the parameters specified in the PRICE wiki. Do you have any thoughts on what the problem might be?

Thanks!
Andrea

2018-06-25 15:55:10.272 INFO Estimating maxpos...
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceEstimateModel@4dc3117c
Could not run gedi.riboseq.javapipeline.PriceEstimateModel@4dc3117c

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceEstimateModel@4dc3117c
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
	at gedi.util.program.GediProgram.run(GediProgram.java:204)
	at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceEstimateModel@4dc3117c
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at gedi.riboseq.javapipeline.PriceEstimateModel.execute(PriceEstimateModel.java:74)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
2018-06-25 15:57:53.986 INFO Finished: gedi -e Price -reads Aligned.sortedByCoord.out.bam -genomic sk1 -prefix bamtest2/0h -D

**Comment by florianerhard** [comment]
Dear Andrea,

could you attach the full logs? As far as I can tell, there appears to be a problem with the annotation. In your `sk1` genome index (what is it, how did you create it?), are there annotated mRNAs?

Best,
Florian

**Comment by alhigdon** [comment]
Hi Florian, 

Thanks for getting back to me. I'm not at all surprised that the issue might be with the annotations. The gtf file I'm am working with was originally formatted somewhat differently than what is standard, and I had to reformat it. I found a small error since I last wrote, and fixing that seemed to allow the clustering step to start, but ultimately I still get the same error message:
![screen shot 2018-07-09 at 2 52 48 pm](https://user-images.githubusercontent.com/22647879/42478284-01e35c72-8389-11e8-86fb-f22649b916f4.png)

The original gtf file looks like this: 
![screen shot 2018-07-09 at 2 54 10 pm](https://user-images.githubusercontent.com/22647879/42478139-7424d352-8388-11e8-8280-16b8e6cf500d.png)

And here is what I reformatted it to (and used for indexing):
![screen shot 2018-07-09 at 2 50 56 pm](https://user-images.githubusercontent.com/22647879/42478178-9a44d0fa-8388-11e8-9e4c-b731bc221975.png)

Is there something required in the gtf file that I'm missing?

Thanks for your help!

Best, 
Andrea

**Comment by florianerhard** [comment]
Dear Andrea,
is there a `.maxPos` file in your output folder? I guess it is empty. Does your gtf not contain any "CDS" lines? Price needs annotated CDS to train the codon model and if you don't supply any, that will fail...

Best,
Florian

**Comment by alhigdon** [comment]
Hi Florian, 

As you suspected, there is no .maxPos file, just .cluster.csv, .estimateData, and .param. 

For the reformatted gtf I only used the "exon" rows from my original gtf. I also tried running with only the "CDS" rows and was not even able to do the indexing step. 

I ran a toy example with just two lines from the gtf - the exon and CDS entries for one gene:
![screen shot 2018-07-09 at 4 29 30 pm](https://user-images.githubusercontent.com/22647879/42481453-574d2126-8397-11e8-8dda-af9d0cd9c8dd.png)
This makes it through the indexing step, but I get the same error message when I run PRICE. 

Is PRICE able to work with only CDS annotations? I noticed that files from ensembl also include "start_codon" entries, which we don't have in our gtf - could this be part of the problem? 

I think my overarching question is - what is the simplest possible gtf file that should still run properly? I'm not clear on which fields are extraneous vs. necessary (for example, the start and end locations are clearly necessary, but are things like gene_biotype necessary?)

Thanks for your help!

Andrea

**Comment by TamaraO** [comment]
I have the same question - what is the minimum required information that the GTF file needs to have? I have exactly the same error, because I also don't have CDS annotated in my GTF file. The GTF file is from de novo transcriptome assembly, so we don't have the CDS information, and that's what we really want to find out.

**Comment by florianerhard** [comment]
Dear Andrea, dear Tamara,

I expanded the [documentation](/erhard-lab/gedi/wiki/Preparing-genomes) on this. You primarily need `exon`s and `CDS` (or alternatively, `start_codon` and `stop_codon`), and a `gene_id` and `transcript_id` for each line.

If you have such incomplete annotation (no UTRs, i.e. all exons are completely covered by CDS), make sure to use the `-novelTranscripts` parameter for PRICE (by default it only identifies ORFs within annotated transcripts from the GTF).

PRICE needs enough known CDS in the GTF to train its codon model. If you want to run it on a de-novo assembled transcriptome, I suggest to merge the de-novo gtf with a gtf containing CDS from the same organism (assuming that there is one).

I hope this helps!
Best,
Florian
