### ISSUE TITLE
ResolveAmbiguities gets stuck

### ISSUE THREAD

**Issue by tkzeng** [erhard-lab/gedi#17]
Hello,

I'm trying to run ResolveAmbiguities, but it seems to get stuck:

<img width="701" alt="screenshot 2018-12-03 05 47 02" src="https://user-images.githubusercontent.com/21118492/49372227-955ebb00-f6bf-11e8-82df-89df3c7bf322.png">

Here is the command I'm using:
`gedi -t tmp -e ResolveAmbiguities -p -r mapped.cit -g gencode.v19.annotation.noMT -s rescued.out -o rescued.cit`

I'm currently running this on a desktop (not a cluster). Also, the first parts of ResolveAmbiguities ran fine, and completed within several minutes.

Do you know what might be going wrong? Thanks so much!

**Comment by florianerhard** [comment]
Dear tkzeng,

unfortunately, CIT2Bam at the moment does not support indels (I guess you mapped using STAR?).

Regarding the initial issue: It probably did not get stuck (what was the CPU usage?), my guess is that it spent a lot of time at the mitochondrial chromosome (usually many ambigous reads). This should be removed anyway!

Best,
Florain

**Comment by tkzeng** [comment]
I tried bowtie instead of STAR and everything is working now. Thank you!
