### ISSUE TITLE
PRICE FDR details

### ISSUE THREAD

**Issue by StevenVerbruggen** [erhard-lab/gedi#18]
Hi Florian,

I was looking for some more details on how the FDR is calculated in PRICE. I did not found these details directly in the manuscript. I found in a closed issue on this forum explaining it is basically a Benjamini Hochberg procedure on the p values coming out of the PRICE ORF inference, but maybe you can give me some more details on this?

Looking forward to hear more on this.
Best regards,

Steven

**Comment by florianerhard** [comment]
Dear Steven,

sorry for my delayed answer.

PRICE first computes p values for each identified ORF using a binomial test (the "p" is estimated from the noise levels close to the ORF, the "n" is the length of the ORF, and the "k" is the number of codons above a certain threshold). If there are overlapping ORFs, the situation is a bit more complicated (how to estimate noise levels and one has to use the generalized binomial distribution - details are in the Online methods of our paper).

The FDR is then computed using the Benjamini-Hochberg procedure for adjusting p values.

I hope these details prove helpful!
Best,
Florian

**Comment by StevenVerbruggen** [comment]
Thank you for these details!
Kind regards,
Steven
