### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by danielrebib** [erhard-lab/gedi#2]
Hello, I am having an issue with the following line: git clone git@github.com:erhard-lab/gedi.git

My output is:

Cloning into 'gedi'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by florianerhard** [comment]
https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories

**Comment by danielrebib** [comment]
Thanks! I used git clone https://git@github.com/erhard-lab/gedi.git as it was easier than setting up an SSH link.

BTW, the PRICE releases link results in 404 error: https://github.com/florianerhard/gedi/releases. Is there a new link?
