### ISSUE TITLE
Issue Preparing a genome

### ISSUE THREAD

**Issue by JoBo1212** [erhard-lab/gedi#2]
Hey! 
When i try to prepare a genome like instructed
 gedi -e IndexGenome -organism homo_sapiens -version 75 -p -nobowtie -nostar
then I get the following error:
"/ Creating kallisto index homo_sapiens.75.gtf.kallisto        Calling kallisto index -i homo_sapiens.75.gtf.kallisto homo_sapiens.75.gtf.transcripts.fasta
An error occurred: Cannot run program "kallisto": error=2, No such file or directory"

What can I do to fix that? Would really like to use your program :-)

Thanks
Jonathan

**Comment by florianerhard** [comment]
Dear Jonathan,

sorry, I didn't update the documentation for that. IndexGenome now can create indices for bowtie, STAR and kallisto. If you don't need them, you don't have to create them. For the moment, also use the `-nokallisto` parameter (in the next release, we will simply skip this step with a warning, if kallisto is not available).

Best,
Florian

**Comment by JoBo1212** [comment]
Thanks! I didnt know what kallisto was, but now i will simply install it :-)
