### ISSUE TITLE
Error could not load storage

### ISSUE THREAD

**Issue by aleighgreen** [erhard-lab/gedi#20]
gedi -e Slam -reads 24h.bam -genomic mus_musculus.90 -prefix slam/24h -progress -plot | echo > error.txt
2019-03-12 12:37:07.230 INFO Discovering classes in classpath
2019-03-12 12:37:07.930 INFO Preparing simple class references
2019-03-12 12:37:08.533 INFO Gedi version 1.0.2 (JAR) startup
2019-03-12 12:37:08.535 INFO Command: gedi -e Slam -reads 24h.bam -genomic mus_musculus.90 -prefix slam/24h -progress -plot
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

**Error:
Could not load storage!**

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

2019-03-12 12:37:08.777 INFO Finished: gedi -e Slam -reads 24h.bam -genomic mus_musculus.90 -prefix slam/24h -progress -plot
2019-03-12 12:37:08.779 INFO Took 2s 502ms

**Comment by florianerhard** [comment]
Dear Al,

could you call the program with the `-D` parameter to get a more verbose error message?

Best,
Florian

**Comment by aleighgreen** [comment]
`gedi -e Slam -D -reads 24h.bam -genomic mus_musculus.90 -prefix slam/24h -progress -plot`

Gives the same error. Is 24h.bam a sample file that is bundles with gedi?

**Comment by aleighgreen** [comment]
Otherwise we thought that might be the error

**Comment by florianerhard** [comment]
You are right. You need mapped reads in bam or cit format! (see Documentation)!

**Comment by aleighgreen** [comment]
Thanks, we're just testing if we're running the software correctly, do you make any sample bams available somewhere? Rather than us doing something like getting the fastq from SRA from Herzog 2017 and reprocessing those to test if we have anything? 

Thanks!

**Comment by florianerhard** [comment]
I updated the [Documentation](https://github.com/erhard-lab/gedi/wiki/GRAND-SLAM#run-grand-slam) on this: The 24h data is now available for testing purposes!

**Comment by aleighgreen** [comment]
Awesome!! Thank you, excited to test it out tomorrow and discover more bugs.

**Comment by aleighgreen** [comment]
Thanks Florian, 

Just checking on the bams on the zendo, and I'm a little confused about this point. 

"GSM2666816,GSM2666817,GSM2666818,GSM2731767,GSM2731768,GSM2731769 against the Mouse genome (**mm10, gtf from Ensembl 90**)."

Mouse genome mm10 is ensembl 95 right? Not 90?

**Comment by florianerhard** [comment]
mm10 is the current genome assembly, it is there for several years already, and used in ensembl since version 68!

**Comment by aleighgreen** [comment]
Apologies Florian, the different names + numbering systems for genomes always gets me turned around.
