### ISSUE TITLE
How to run GRAND-SLAM with no 4su control experiemnt

### ISSUE THREAD

**Issue by aleighbrown** [erhard-lab/gedi#22]
Hello, 

We're a bit confused about this section in the readme:
"Regression model for the T>C rate in old RNA

Make sure that you either have samples without 4sU to let GRAND-SLAM estimate the regression model from these data, or to have the regression model for you protocol/sequencer. For the former, make sure that the names of the conditions (i.e. given in the metadata of the CIT file, or by the name of the BAM file) include "no4sU" (or, alternatively, use the -no4sUpattern parameter to tell GRAND-SLAM how to identify them). For the latter, specify it via the -errlm parameter."

So, if we DO not have no 4sU condition and we want to estimate error from the other rates, we run as so:
`gedi -e Slam -errlm default -genomic /SAN/vyplab/FUS_RNA/grand_slam_genomes/mus_musculus.95 -prefix /SAN/vyplab/ALB_SLAM/3S2_24hWT -progress -plot -D -reads /SAN/vyplab/FUS_RNA/Marta_SLAM/ResultsTagged/3S2/3S2_unique.bam`?

with the -errlm flag? and what does the argument need to be to the -errlm flag? and there is also a -errlm2 flag, what is that?

**Comment by aleighgreen** [comment]
Got this running using the command
"gedi -e Slam -errlm TA*1.434"

But I'm not sure if that's the right coefficient for TA, in our data? Unclear to me how we're meant to be estimating. Thanks!

**Comment by aleighbrown** [comment]
Hi, just following up on this question... 

Do you have additional guidance for how to do this?

**Comment by tsekara** [comment]
Hi

@aleighbrown  Were u able to resolve the question? I also don't have no4SU samples.Kindly guide me

**Comment by aleighbrown** [comment]
Running using the -errlm parameter gives results; and from my understanding of their methods paper it's preferable to estimate the error from within experiment in any case.  

We run using the following command

```gedi -e Slam -allGenes -errlm TA*1.434 -genomic human -prefix /yourdesiredfilepath/test_all_genes -progress -D -reads /path/to/your.bam```
