### ISSUE TITLE
GRAND-SLAM column interpretation 

### ISSUE THREAD

**Issue by aleighbrown** [erhard-lab/gedi#23]
GRAND-Slam outputs a prefix.tsv file, which appears to contain helpful information on half lives, but we're a little confused how to interpret the columns.

Column | Understanding
-- | --
Gene | understand
Symbol | understand
merged_5S3_6S4 Readcount | ?
merged_5S3_6S4 0.05 quantile | ?
merged_5S3_6S4 Mean | ?
merged_5S3_6S4 MAP | ?
merged_5S3_6S4 0.95 quantile | ?
merged_5S3_6S4 alpha | alpha of the beta distribution of the gene
merged_5S3_6S4 beta | beta of the beta distribution
merged_5S3_6S4 Conversions | ?
merged_5S3_6S4 Coverage | ?
merged_5S3_6S4 Double-Hits | ?
merged_5S3_6S4 Double-Hit Coverage | ?
merged_5S3_6S4 min2 | ?
Length | ?

How should we find the RNA-half life then? is the MAP our decay rate which can be transformed into half-life with the simple log(2)/delta?

Thank you!!

**Comment by aleighgreen** [comment]
Column | Understanding
-- | --
Gene | understand
Symbol | understand
merged_5S3_6S4 Readcount | ?
merged_5S3_6S4 0.05 quantile | refers to the beta distribution described by the alpha and beta
merged_5S3_6S4 Mean | refers to the beta distribution described by the alpha and beta
merged_5S3_6S4 MAP | **estimator to be used for decay rate**?
merged_5S3_6S4 0.95 quantile | refers to the beta distribution described by the alpha and beta
merged_5S3_6S4 alpha | alpha of the beta distribution of the gene
merged_5S3_6S4 beta | beta of the beta distribution
merged_5S3_6S4 Conversions | ?
merged_5S3_6S4 Coverage | ?
merged_5S3_6S4 Double-Hits | ?
merged_5S3_6S4 Double-Hit Coverage | ?
merged_5S3_6S4 min2 | ?
Length | gene length in bp

Upon further reading of the paper, I believe the correct steps are to use the MAP across several time points to estimate decay rate which can be translated into half life.
