### ISSUE TITLE
gedi.riboseq.javapipeline.PriceClusterReads

### ISSUE THREAD

**Issue by BioMLBoston** [erhard-lab/gedi#27]
Hi,

I'm trying to run the PRICE on a ribo-seq experiment but I've got an error about my reads are not sorted. I used STAR and aligned my reads to the genome as it is explained in the tutorial.
here is my error

_2019-06-02 17:14:24.789 INFO Command: gedi -e Price -reads hsv1/star_outSRR1523654OAligned.sortedByCoord.out.bam -genomic homo_ensPrice -prefix Srrtest
2019-06-02 17:14:26.691 INFO Discovering classes in classpath
2019-06-02 17:14:27.409 INFO Preparing simple class references
2019-06-02 17:14:27.849 INFO Gedi 1.0.2 (JAR) startup
2019-06-02 17:14:28.731 INFO Reading oml /home/av33b/.gedi/genomic/homo_ensPrice.oml
2019-06-02 17:14:28.756 INFO Done reading oml /home/av33b/.gedi/genomic/homo_ensPrice.oml
2019-06-02 17:14:33.129 INFO Clustering reads
2019-06-02 17:14:33.153 INFO Estimating maxpos...
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@4907c402
Could not run gedi.riboseq.javapipeline.PriceClusterReads@4907c402
Input not sorted: 1+:14116-14253	[1] x3 36|65|36 > 1+:14100-14295	[1] x3 94|7|94	M94TGr	M96GAr	M109CTr	M157AGr

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
..._

Also this is an example of my bam file:

_SRR1523654.1.1	99	chr5	146772831	255	1S100M	=	146772866	136	NTCCCTGCCTGGCCTTCCCAACCCAGGAAAGAGAAGGATTTGAAAGCAACAATGAGAAAGATGCCTGAGCAAACACGGGCACAATCAAGCAGGNGGAAGAA	#0;;;?###############################################################################################	NH:i:1	HI:i:1	AS:i:184	nM:i:7	NM:i:5	MD:Z:50C1A7G14T16T7	jM:B:c,-1	jI:B:i,-1
SRR1523654.1.1	147	chr5	146772866	255	101M	=	146772831	-136	GAGTTGAAAGCAACAATAAGAAAGAGGCCTGAGCAAACACTGGCACAATCAAGCAGGTGGAAGAAATGGTTGGGTCTTGGCATTTTAATAACCGTTCAAAG	################################?>7)=BBBA=4>.8<=(*=7;>0;BA4=?*?7:1)0)115AC7<AC?<A7A?A<,?0?2)<2+,+777=	NH:i:1	HI:i:1	AS:i:184	nM:i:7	NM:i:3	MD:Z:2T12C75A9	jM:B:c,-1	jI:B:i,-1
SRR1523654.2.1	99	chr8	120594690	255	1S100M	=	120594724	135	NCCAGGTCAAAATCAGACTGAAGGTACATAATCCCTGGATAATTGGGTCTGGTAANTTCCTCTGGCATGGTTGGCCTGAAGGCATTAGTGCGCNGGAGATG	#1:<+@AACBBBB<>B7A+7=<CC@<A?>BBABBBB>=BB?A4***:)9=BA*?=#0<(5AAAA9=BBAB.=<6;>;=;>>@###################	NH:i:1	HI:i:1	AS:i:195	nM:i:1	NM:i:3	MD:Z:54C26T10A7	jM:B:c,-1	jI:B:i,-1
SRR1523654.2.1	147	chr8	120594724	255	101M	=	120594690	-135	TGGATAATTGGGTCTGGTAACTTCCTCTGGCATGGTTGGCCTGAAGGTATTAGTGCGCAGGAGATGATTCAAACTTCCATGGGTCCCATTATTAGGAGCTG	>AA>::(?<9@@B@@5(;--;(,(@>;;?;)7DBECECC;AF@=)@4<)FB<FDD6@??C1*9D?C<?1*4@2AD@@>>AIFFFE4C<FD8FDAD;;D;:+	NH:i:1	HI:i:1	AS:i:195	nM:i:1	NM:i:0	MD:Z:101	jM:B:c,-1	jI:B:i,-1
SRR1523654.3.1	163	chrM	2977	255	101M	=	2995	118	GTTTACGACCTCGATGTTGGATCAGGACATCCCAATGGTGCAGCCGCTATTAAAGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTTCAGAC	@@<DDBDD>AFFA@:<22AAEHGC><?E99C@?FBDD<9D<@<DFFE:@884@EFE74):(.;BDCC@BCCB@BBBB>5(5>>3;9@??BABBA>ABD@@>	NH:i:1	HI:i:1	AS:i:191	nM:i:3	NM:i:1	MD:Z:33G67	jM:B:c,-1jI:B:i,-1
SRR1523654.3.1	83	chrM	2995	255	100M1S	=	2977	-118	GGATCAGNACATCCCAATGGTGCAGCCGCTATTAAAGGTTCGTTTNTTCAACGATTAAAGTCCTACGTGATCTGAGTTCAGACCGGAGTAATCCAGGCCGN	##################?:88':===?B@@@@@@><@AAAA;--#>=8(.AB?ABBBBBBAA?)ABBBA=BABABBA7A=3=CBA9BBA7BBAAAAA:1#	NH:i:1	HI:i:1	AS:i:191	nM:i:3	NM:i:4	MD:Z:7G7G29G51T2	jM:B:c,-1	jI:B:i,-1
SRR1523654.4.1	163	chr15	60772108	255	101M	=	60772120	112	TGAAGAATGTGGGTATGTGGAATGAAGAGAAAGGGCGTTCTAGACAGACCAGCACAAGTGTCAAAAGACAAAAATTTGACACATCTAAAGATCTCAGTTGG	CCCFFFFFHFHHHFHJIIJJJJJJJJJJJJJJJJJJJIJIJJIJJJJJIJGHIIJJJJGIHHHHHHHFFFFEDDEEDDEDDDDDDDDDDDDDDEDDDDEDD	NH:i:1	HI:i:1	AS:i:198	nM:i:0	NM:i:0	MD:Z:101	jM:B:c,-1	jI:B:i,-1
SRR1523654.4.1	83	chr15	60772120	255	100M1S	=	60772108	-112	GTATGTGNAATGAAGAGAAAGGGCGTTCTAGACAGACCAGCACAAGTGTCAAAAGACAAAAATTTGACACATCTAAAGATCTCAGTTGGCCTTATTGCGAN	DDBB?5,#DEEDDDDDDEEDDFFGHHGGJJIJJJHHIGIIIIJJJJJJJJJJJJIIJJJJJJJJHHHHFIIIHJJJJJJJJJIJJJJJHHHHHFFFFD=1#	NH:i:1	HI:i:1	AS:i:198	nM:i:0	NM:i:1	MD:Z:7G92jM:B:c,-1	jI:B:i,-1
SRR1523654.5.1	99	chr6	153293472	255	1S100M	=	153293507	727	NTTTGAGCATCTTTTTTGAGAGAAGTCTGGGCTGCTGATTTCTGATCAGAAGCCANTGGGGTTCTGAACATAACATATTCTCTGGTTGAAGCANGAGGTGA	#1=BDDDEGHHHHJJJJJGJIJIJIIGIJIJJJJIJJJJJIJJJIHGICGHJFIJ#.5CHE8=EFFBCDFDEDEECDEEFEDDDDDDDDDDDD#,2?@?AD	NH:i:1	HI:i:1	AS:i:195	nM:i:2	NM:i:3	MD:Z:44A9G37T7	jM:B:c,-1	jI:B:i,-1_

Do you have any suggestion?

Thanks,
Amir

**Comment by florianerhard** [comment]
Dear Amir,
you did 2x101bp paired-end sequencing for ribo-seq?

If this is really the case (and you are not trying to process RNA-seq data with price): Price does not support paired-end bam files (the reason is that this step of the program expects sorted read mappings, and it is impossible to efficiently pull out both reads of a pair from a bam file and do this in a sorted fashion). 

One easy way of dealing with that: Just throw away the fastq with the second reads, they don't contribute anything. 

Another option: convert the bams to cit and correct their sorting:
```bash
gedi -e Bam2CIT anyname.cit star_outSRR1523654OAligned.sortedByCoord.out.bam
gedi -e CorrectCIT anyname.cit
```
and then use the cit file instead of the bam file!

Florian
