### ISSUE TITLE
Where do alignments go? 

### ISSUE THREAD

**Issue by stephenhkwong** [erhard-lab/gedi#29]
Dear Florian,

I have ran this pipeline to align 4 fastq files in test.json,

gedi -e Pipeline -r parallel -j test.json -n reads_mapping shortread_mapping.sh

I saw it is running well, but I can not find where are bam files ??

By the way, Thanks so so much for the tool!

below are json file:

{
"datasets": [
                {"fastq": "ribo1_rep1_S1_R1_001.fastq.gz", "name": "ribo1"},
                {"fastq": "ribo2_rep1_S1_R1_001.fastq.gz", "name": "ribo2"},
                {"fastq": "ribo3_rep1_S2_R1_001.fastq.gz", "name": "ribo3"},
                {"fastq": "ribo4_rep1_S1_R1_001.fastq.gz", "name": "ribo4"}

        ],
"references": {"mus_musculus.97": "both", "mouse_rRNA": "rRNA"}
}

**Comment by florianerhard** [comment]
Dear Stephen,

you have to set `keepbams` to true. You can do this either in the json file:
```
...
"references": {"mus_musculus.97": "both", "mouse_rRNA": "rRNA"},
"keepbams"=true
}
```

or via the command line call to gedi: 
```
gedi -e Pipeline -r parallel -j test.json --keepbams=true -n reads_mapping shortread_mapping.sh
```

**Comment by stephenhkwong** [comment]
ah I see ! Thanks Florian!

do you know where can I find out all the available options like --keepbams=true, I couldn't find it by gedi -e Pipeline -h shortread_mapping.sh , etc

Thanks again.
