### ISSUE TITLE
how to install Rserve in my system (redhat)

### ISSUE THREAD

**Issue by stephenhkwong** [erhard-lab/gedi#31]
My system has R version 3.5.1, but there's no Rserve, the error message below,

sh-4.2$ R CMD Rserve
/opt/microsoft/ropen/3.5.1/lib64/R/bin/Rcmd: line 62: exec: Rserve: not found

How do I install Rserve package ? Should I install it within the R ? 

Thanks!

**Comment by florianerhard** [comment]
https://www.rforge.net/Rserve/down.html
