### ISSUE TITLE
adaptor trimming

### ISSUE THREAD

**Issue by stephenhkwong** [erhard-lab/gedi#32]
Hi Florian,
my samples adaptor is followed by 5 more random nucleotides which serve as UMI to remove duplicated reads. How can I instruct the pipeline to remove this 5 nt before the mapping? Should I add 5 NNNNN to the end of adaptor in json file like this ?

{"fastq": "S1_R1_001.fastq.gz", "name": "Ctrl","adapter": "CGTAAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNN"}

Thanks!

**Comment by florianerhard** [comment]
Dear Stephen,
at the moment, this is not possible with our pipeline (we are working on that)!

Sorry,
Florian
