### ISSUE TITLE
Error when preparing genomes

### ISSUE THREAD

**Issue by xuhangliu** [erhard-lab/gedi#33]
Dear Florian,

I got the error msg "ERROR: too many files specified." when I tried to prepare genomes using the following cmd: 
gedi -e IndexGenome -s /mnt/evo860/hits-analysis/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -a /mnt/evo860/hits-analysis/genomes/Mus_musculus/UCSC/mm10/Annotation/mm10.gencodeVM16.comp.UCSC_format.gtf -n mm10.gencodeVM16

Could you please help me figure it out? Thank you!
Xuhang

**Comment by florianerhard** [comment]
Dear xuhangliu,

could you please rerun with `-D`? (`gedi -e IndexGenome -D -s ...`)

thanks, 
Florian
