### ISSUE TITLE
gedi -e FastqFilter error SEVERE Failed running Rserve!

### ISSUE THREAD

**Issue by jflucier** [erhard-lab/gedi#39]
Helllo,

trying to run gedi FastqFilter and I get the following error. I have R v3.5.0 installed with the following libraries ggplot2, reshape2, Rserve, ROCR and data.table as indicated in the Installing and configuring PRICE procedure. As you can see below, the R libraries are loaded properly in the R console.

Thanks for all your help, 

JF

`
|08:48:28|jflucier@ip32-centos7:[GSM1289257]> gedi -e FastqFilter -D -ld GSM1289257.readlengths.tsv -min 18 GSM1289257.lane.clean > GSM1289257.fastq
2020-03-19 08:51:44.204 INFO Command: gedi -e FastqFilter -D -ld GSM1289257.readlengths.tsv -min 18 GSM1289257.lane.clean
2020-03-19 08:51:44.538 INFO Discovering classes in classpath
2020-03-19 08:51:44.841 INFO Preparing simple class references
2020-03-19 08:51:44.993 INFO Gedi 1.0.2 (JAR) startup
2020-03-19 10:48:23.216 SEVERE Failed running Rserve!
java.lang.RuntimeException: R returned error code 127
	at gedi.util.r.RConnect.<init>(RConnect.java:70)
	at gedi.util.r.RConnect.getInstance(RConnect.java:42)
	at gedi.util.r.RConnect.R(RConnect.java:57)
	at gedi.util.plotting.GGPlot.prepareR(GGPlot.java:101)
	at gedi.util.plotting.GGPlot.png(GGPlot.java:84)
	at executables.FastqFilter.start(FastqFilter.java:254)
	at executables.FastqFilter.main(FastqFilter.java:65)

An error occurred: Could not connect to R!
java.lang.RuntimeException: Could not connect to R!
	at gedi.util.r.RConnect.<init>(RConnect.java:89)
	at gedi.util.r.RConnect.getInstance(RConnect.java:42)
	at gedi.util.r.RConnect.R(RConnect.java:57)
	at gedi.util.plotting.GGPlot.prepareR(GGPlot.java:101)
	at gedi.util.plotting.GGPlot.png(GGPlot.java:84)
	at executables.FastqFilter.start(FastqFilter.java:254)
	at executables.FastqFilter.main(FastqFilter.java:65)
Caused by: java.lang.RuntimeException: R returned error code 127
	at gedi.util.r.RConnect.<init>(RConnect.java:70)
	... 6 more
2020-03-19 10:48:23.223 INFO Finished: gedi -e FastqFilter -D -ld GSM1289257.readlengths.tsv -min 18 GSM1289257.lane.clean
|10:48:23|jflucier@ip32-centos7:[GSM1289257]> R

R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> library("ggplot2")
> library("reshape2")
> library("Rserve")
> library("ROCR")
Loading required package: gplots

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

> library("data.table")
data.table 1.12.8 using 12 threads (see ?getDTthreads).  Latest news: r-datatable.com

Attaching package: ‘data.table’

The following objects are masked from ‘package:reshape2’:

    dcast, melt

> quit()
Save workspace image? [y/n/c]: n

`

**Comment by florianerhard** [comment]
Dear JF,

does the command `R CMD Rserve --no-save --no-restore --silent` work (i.e. is the Rserve package properly installed)?

Florian

**Comment by jflucier** [comment]
no that exactly the problem.

this command works: R CMD /home/jflucier/R/x86_64-pc-linux-gnu-library/3.6/Rserve/libs/Rserve

tried yesterday to get that command (i.e. R CMD Rserve --no-save --no-restore --silent) working but the only way i found to do this is to do a link in R bin folder. I cannot do this as I dont have access to R bin dir in cluster environment.

Still trying to figure out how to do this. I saw in the gedi code that a config file (build/classes/ressources/default.config) is read and loaded by Config.java to change the call Rserve command but cannot set the default DEFAULT_RSERVE_COMMAND.

I tried changing default config to this and some other keys but cannot get this to work:

{
"email": "",
"templates": [
	"file://${wd}/${name}",
	"classpath://Gedi/resources/templates/${name}",
	"classpath://Gedi/resources/pipeline/${name}",
	"classpath://Gedi/resources/${name}"
	],
"DEFAULT_RSERVE_COMMAND": "R CMD /home/jflucier/R/x86_64-pc-linux-gnu-library/3.6/Rserve/libs//Rserve --no-save --no-restore --silent"
}

When I start Rserve using above command, I can see that Reserve is up and running using telnel command:

$ telnet localhost 6311
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Rsrv0103QAP1

--------------

On debug R shell, thuis comamnd outputs:

Rserve: Ok, ready to answer queries.
 - create_server(port = 6311, socket = <NULL>, mode = 0, flags = 0x4000)
INFO: adding server 0x5654eb777740 (total 1 servers)
INFO: accepted connection for server 0x5654eb777740, calling connected
connection accepted.
sending ID string.

Thanks alot for your help,
JF

**Comment by florianerhard** [comment]
Dear jflucier,

I am sorry, changing these defaults is planned, but just not yet implemented :(

As a simple workaround, create a script named `R` into a folder that takes precedence over the folder of your standard `R` in the PATH variable:

```bash
#!/bin/bash

R="/usr/bin/R"
A="$@"
if [ "$A" == "CMD Rserve --no-save --no-restore --silent" ]
then
	$R CMD /home/jflucier/R/x86_64-pc-linux-gnu-library/3.6/Rserve/libs//Rserve --no-save --no-restore --silent
else
	$R $@
fi
```

**Comment by jflucier** [comment]
this solved the problem.

If and when defaults are implemented, a way variable to specify where the genome index are found would be nice instead of having the default /home/$USER/.gedi/genomic folder.

The gedi -e IndexGenome  provides a mean to oiutput index in a user specified folder but did not find a way to pass that information to the other gedi calls like FastqFilter, MergeSam, etc.

Create a symbolic link in my home directory to bypass this problem. 

Thank for your help, JF
