### ISSUE TITLE
Randomized Adapters

### ISSUE THREAD

**Issue by JoBo1212** [erhard-lab/gedi#4]
Hey,
not an issue with the program, but more of a question.
My sequencing reads contain randomized adapter sequences on the 3' and 5' ends in addition to an adapter on the 3' end. ( Like this: 5'-XXXX-Read-XXXX-Adapter-3')

Is it possible to clip the adapter as well as the four random bases on each side from the reads in your pipeline, or would you recommend that I create BAM files "manually" and then put them into PRICE?

PS: I realized that STAR does require 30 GB of ram for building a human genome index, therefore I think I wont be able to use STAR on my device, or is there a workaround?

Thank a lot,
Jonathan

**Comment by florianerhard** [comment]
Dear Jonathan,

first, regarding STAR: You could also use bowtie, which only takes 4GB of memory for the human genome. It is supported by the pipeline as well (see below, ``shortread_mapping.sh`` uses bowtie by default).

regarding the random barcodes: I had something like that already (only at the 5' end, and containing a library barcode). I adapted my code and tested it with a toy example, such that your layout is also supported. 

My test files were: random.json
```json
{
"references": {"h.ens90": "both"},
"datasets": [
	{"fastq": "random.fastq",
		"name": "Test", 
		"barcodes": { "leading": 6, "trailing": 6 }
	}
	],
"adapter": "ACACTCTTTCCCTACAC"
}
```

random.fastq
```
@0
AAAAAAATGTTCAGCATTCAGGTGATCAGCAGGACTAAAAAAACACTCTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@1
AAACAAATGTTCAGCATTCAGGTGATCAGCAGGACTAAAAAAACACTCTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@2
AAAAAACAGCAGGACTGTCTCCAGCACGGAGCAAAAAAACACTCTTTCCCT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@3
AAAAAAATGTTCAGCATTCAGGTGATCAGCAGGACTAAAAAAACACTCTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
```

Assuming you have a prepared genome h.ens90, you can generate the pipeline with
```bash
gedi -e Pipeline  -r parallel -j random.json --tmp=`pwd`/tmp shortread_mapping.sh finish.sh
```
Then run the start.bash in ``random/scripts``. This should generate ``random/random.cit`` with the following content:

```
gedi -e ViewCIT random/random.cit
12+:4613565-4613595     0: [2] x1
12+:4613585-4613611     1: [1] x1
```

For your Ribo-seq experiment, you may then generate the pipeline with:
```bash
gedi -e Pipeline  -r parallel -j ribo.json --tmp=`pwd`/tmp shortread_mapping.sh report.sh price.sh finish.sh
```

**Comment by JoBo1212** [comment]
Hey Florian,

thank you so much for the reply. I am still working my way through the functionalities of your PRICE and havent quite understood every detail, but I take from your answer that it should be possible to remove these random nucleotides. Thanks for creating that solution!

I have encountered another issue when setting up PRICE on my laptop, aswell as the mac workstation that we have here in the lab. I think i successfully created the genome index and ran PRICE on the example data, but when starting the genome browser i get the following error:

b140-mac04:Price_1.0.2 bohlen$ gedi -e RiboView -a price -g homo_sapiens.75 -l RAB2A
2018-03-20 15:22:49.633 INFO Command: gedi -e RiboView -a price -g homo_sapiens.75 -l RAB2A
2018-03-20 15:22:49.821 INFO Discovering classes in classpath
2018-03-20 15:22:49.963 INFO Preparing simple class references
2018-03-20 15:22:50.086 INFO Gedi 1.0.2 (JAR) startup
2018-03-20 15:22:50.227 INFO Reading oml /Users/bohlen/.gedi/genomic/homo_sapiens.75.oml
2018-03-20 15:22:50.233 INFO Done reading oml /Users/bohlen/.gedi/genomic/homo_sapiens.75.oml
An error occurred: null
2018-03-20 15:22:51.095 INFO Finished: gedi -e RiboView -a price -g homo_sapiens.75 -l RAB2A

Maybe it is something really obvious, but the fact that i encountered it on two independent systems reinforced me to ask about it. Does "null" mean that some file is missing? The price model is in the price folder, as indicated by the -a variable... Thank you so much for your help :-)

Jonathan

**Comment by florianerhard** [comment]
Dear Jonathan,

could you run it again with ``-D`` flag? This provides a more meaningful and verbose error message!

Florian

**Comment by JoBo1212** [comment]
Hey Florian, 
here it is: 

2018-03-21 08:09:23.494 INFO Command: gedi -e RiboView -a price -g homo_sapiens.75 -l RAB2A -D
2018-03-21 08:09:23.669 INFO Discovering classes in classpath
2018-03-21 08:09:23.688 INFO Preparing simple class references
2018-03-21 08:09:23.737 INFO Gedi 1.0.2 (JAR) startup
2018-03-21 08:09:23.954 INFO Reading oml /Users/bohlen/.gedi/genomic/homo_sapiens.75.oml
2018-03-21 08:09:23.966 INFO Done reading oml /Users/bohlen/.gedi/genomic/homo_sapiens.75.oml
An error occurred: null
java.lang.NullPointerException
	at gedi.util.functions.EI.wrap(EI.java:175)
	at gedi.util.functions.EI.files(EI.java:335)
	at executables.RiboView.start(RiboView.java:256)
	at executables.RiboView.main(RiboView.java:83)
2018-03-21 08:09:25.092 INFO Finished: gedi -e RiboView -a price -g homo_sapiens.75 -l RAB2A -D

Thanks!
Jonathan

**Comment by JoBo1212** [comment]
Hey Florian, 

here also an Update ion the Adapter trimming, i tried your approach and it didnt really work. Most likely, there is still something wrong with my setup of PRICE. Here is the json file that i created:
File name "pipeline2.json"

{
"references": {"homo_sapiens.75": "both"},
"datasets": [
	{"fastq": "Test.fastq", "name": "Test", "barcodes": { "leading": 4, "trailing": 4 }}
	
	
	],
"adapter": "TGGAATTCTCGGGTGCCAAGG "
}

And here is the command i used to create the start.bash file:
gedi -e Pipeline -r parallel -j pipeline2.json --tmp=`pwd`/tmp shortread_mapping.sh finish.sh

Then I executed the commands from start.bash in the terminal (copy-paste). It did not create a cit file and in the log there are a bunch of error messages... I attached the log files.

Thank you very much for your help. I hope I am not stealing too much of your time. I compared several tools for Ribo-seq data analysis and I liked yours the most, particularly because you state it is compatible with Harringtonine samples, can detect none AUG start codons. Obviously I dont have a strong bioinformatics background but i am trying my best. 

Let me know if you need anything else.

[log.zip](https://github.com/erhard-lab/gedi/files/1833936/log.zip)

Thank you very much!
Jonathan

**Comment by florianerhard** [comment]
Dear Jonathan,

I appreciate your input, I really would like to make my tool usable by anyone...

About the first problem (NullPointerException on RiboView): Is there a xxx.orfs.cit.metadata.json in your price folder? Did you call RiboView from the directory containing the price directory (not from within!)

About the error message with your random barcodes: Have you updated your price version (not from the release, but from git?)

what you have to do is:

```
git clone git@github.com:erhard-lab/gedi.git
buildworkspace.sh build
```
A directory ``build`` is created containing the same structure as each release.

Best,
Florian

**Comment by JoBo1212** [comment]
Hey Florian,
thanks for your reply! About the first problem: No, there is no xxx.orfs.cit.metadata.json file in the price folder, here is the content of the price folder:
[price.zip](https://github.com/erhard-lab/gedi/files/1835323/price.zip)

And yes, I executed the command from the directory containing the price folder.

Second problem: 
I had not updated to the recent version from git, thanks for making me aware of such a thing.
I downloaded the latest version like this:
`git clone git@github.com:erhard-lab/gedi.git`

```
b140-mb10:PRICE bohlen$ git clone git@github.com:erhard-lab/gedi.git
Cloning into 'gedi'...
remote: Counting objects: 7195, done.
remote: Compressing objects: 100% (1646/1646), done.
remote: Total 7195 (delta 789), reused 873 (delta 322), pack-reused 5158
Receiving objects: 100% (7195/7195), 201.00 MiB | 94.00 KiB/s, done.
Resolving deltas: 100% (3575/3575), done.
Checking out files: 100% (1929/1929), done.

```
But when i try the next line i get this:
```
b140-mb10:gedi bohlen$ buildworkspace.sh build
-bash: buildworkspace.sh: command not found
```
Doesnt matter if i call from inside the gedi folder or the folder containing the gedi folder...
Is that line not supposed to be executed from the terminal and referring to something else?
Sorry if I am missing something basic..

Thanks very much,
Jonathan

**Comment by florianerhard** [comment]
Dear Jonathan,

upon git clone, a new directory ``gedi`` is created, and in it there's the file ``buildworkspace.sh``. So you have to ``cd gedi`` first!

**Comment by JoBo1212** [comment]
Hey Florian,
there is no file called `buildworkspace.sh` in the gedi folder, there is only a file called `buildworkspace.bash`. Is that what you meant?
As I told you, I tried to call `buildworkspace.sh build` inside the gedi folder, it returned the error shown above.
Thanks,
Jonathan

**Comment by florianerhard** [comment]
Oh sorry, it is called ``buildworkspace.bash``. So you have to call ``buildworkspace.bash build`` from within the ``gedi`` folder, of course!

**Comment by florianerhard** [comment]
Dear Jonathan,

I expanded the wiki for this issue:

Make sure that you have the correct directory structure: You should have a directory containing the `gedi` script, the file `gedi.jar` as well as the subdirectory `lib` containing several `jar` files

This directory (containing the `gedi` script) should be in your `$PATH` variable!

Best,
Florian
