### ISSUE TITLE
MergeSam error

### ISSUE THREAD

**Issue by jflucier** [erhard-lab/gedi#40]
Hi

I get the following error when running gedi -e MergeSam:

`

|10:18:23|jflucier@ip32-centos7:[GSM1289257]> gedi -t . -e MergeSam -D -genomic ${__ANN_REF__}.gtf -t $__OUTPATH__/scripts/${__RUN_NAME__}.prio.csv -prio $__OUTPATH__/scripts/${__RUN_NAME__}.prio.oml -chrM -o $__RUN_NAME__.cit
2020-03-20 10:18:37.278 INFO OS: Linux 4.15.0-64-generic amd64
2020-03-20 10:18:37.327 INFO Java: Java HotSpot(TM) 64-Bit Server VM 1.8.0_161-b12
2020-03-20 10:18:37.523 INFO Discovering classes in classpath
2020-03-20 10:18:37.685 INFO Preparing simple class references
2020-03-20 10:18:37.820 INFO Gedi version 1.0.2 (JAR) startup
2020-03-20 10:18:37.822 INFO Command: gedi -e MergeSam -D -genomic 00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf -t /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.csv -prio /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.oml -chrM -o GSM1289257.cit
An error occurred: gedi.core.region.ArrayGenomicRegion cannot be cast to java.lang.String
java.lang.ClassCastException: gedi.core.region.ArrayGenomicRegion cannot be cast to java.lang.String
	at gedi.util.ArrayUtils.index(ArrayUtils.java:674)
	at gedi.util.ArrayUtils.index(ArrayUtils.java:668)
	at gedi.util.functions.ExtendedIterator.index(ExtendedIterator.java:957)
	at executables.MergeSam.start(MergeSam.java:217)
	at executables.MergeSam.main(MergeSam.java:84)
2020-03-20 10:18:38.750 INFO Finished: gedi -e MergeSam -D -genomic 00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf -t /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.csv -prio /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.oml -chrM -o GSM1289257.cit

`

I am using Price 1.0.3b.

`
|10:18:58|jflucier@ip32-centos7:[GSM1289257]> whereis gedi
gedi: /home/xroucou_group/apps/Price_1.0.3b/gedi.jar /home/xroucou_group/apps/Price_1.0.3b/gedi

`

My genomic oml file seem ok:

`
|10:22:21|jflucier@ip32-centos7:[GSM1289257]> head -n 100 /home/jflucier/.gedi/genomic/00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.oml
<Genomic>
	<FastaIndexSequenceProvider file="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/saccharomyces-cerevisiae-s288c.genome.fi" />

	<Annotation name="Transcripts">
		<CenteredDiskIntervalTreeStorage file="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.index" />
	</Annotation>
	<NameIndex path="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.names" />
	<GenomicMappingTable from="Transcripts" >
		<Csv file="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcripts.tab" field="transcriptId,proteinId,biotype,source" />
	</GenomicMappingTable>
	<GenomicMappingTable from="Genes" >
		<Csv file="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genes.tab" field="geneId,symbol,biotype,source" />
	</GenomicMappingTable>

	<Info name="bowtie-genomic" info="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic" />
	<Info name="bowtie-transcriptomic" info="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic" />

|10:22:35|jflucier@ip32-centos7:[GSM1289257]> ll /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.index*
-rw-rw-r-- 1 jflucier jflucier 397753 Mar 16 11:08 /nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.index.cit

`

All prio files are there also:

`
|10:24:31|jflucier@ip32-centos7:[GSM1289257]> ls $__OUTPATH__/scripts/${__RUN_NAME__}.prio.*
/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.csv
/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/GSE53268/refseq//scripts/GSM1289257.prio.oml

`

Thanks alot for your help 
JF

**Comment by florianerhard** [comment]
Dear JF,
this looks like a problem inside your GSM1289257.prio.csv. Could you post its contents here? Also, your `-genomic` parameter appears to point to a gtf file. It has to be a name of an indexed genome (or the path to the corresponding oml file).

Florian

**Comment by jflucier** [comment]
Hi Florian,

the content of GSM1289257.prio.csv and GSM1289257.prio.oml:

|10:21:14|jflucier@ip32-centos7:[scripts]> head -n 100 GSM1289257.prio.csv
File	Genome	Transcriptomic	Priority
00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.Genomic.sam	00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf	false	3
00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.Transcriptomic.sam	00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf	true	2
|10:21:18|jflucier@ip32-centos7:[scripts]> head -n 100 GSM1289257.prio.oml
<GenomicRegionFeaturePipeline>


	<FeatureMapping id="Transcript Type">
		<AnnotationFeature data="true" >
			<Transcripts g="genomic"/>
			<Field p="transcriptId" />
		</AnnotationFeature>
		<Transcripts g="genomic" to="biotype" />
	</FeatureMapping>


	<FeatureMapping id="Priority" input="Transcript Type"  >
		<ChainMode c="FirstForAny" />
		<ContainsMapping from="rRNA" to="1" />
		<Default to="" />
	</FeatureMapping>
</GenomicRegionFeaturePipeline>

The -genomic points to an indexed genome, my indexed genome folder contains the following files. My indexed naming includes the .gtf extension:

|10:22:10|jflucier@ip32-centos7:[scripts]> ls  ../../../gtf_1.4/00001-00130-*
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genes.tab
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.1.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.2.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.3.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.4.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.rev.1.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.genomic.rev.2.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.makeref.sh
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.oml
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.index.cit
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.names
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.1.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.2.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.3.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.4.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.rev.1.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcriptomic.rev.2.ebwt
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcripts.fasta
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcripts.fi
../../../gtf_1.4/00001-00130-saccharomyces-cerevisiae-s288c-refseq.transcripts.tab

The temp folder where the command is executed contains the following files:

|10:26:52|jflucier@ip32-centos7:[scripts]> ls -lh ~/temp/fake_slurm_tmp/GSM1289257/
total 20G
-rw-rw-r-- 1 jflucier jflucier 2.5G Mar 19 13:19 00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.Genomic.sam.gz
-rw-rw-r-- 1 jflucier jflucier 2.4G Mar 19 14:15 00001-00130-saccharomyces-cerevisiae-s288c-refseq.gtf.Transcriptomic.sam.gz
-rw-rw-r-- 1 jflucier jflucier   67 Mar 18 08:56 adapter.fasta
-rw-rw-r-- 1 jflucier jflucier 7.1G Mar 19 10:48 GSM1289257.fastq
-rw-rw-r-- 1 jflucier jflucier 7.1G Mar 17 18:10 GSM1289257.fastq.bak
-rw-rw-r-- 1 jflucier jflucier 192M Mar 18 08:56 GSM1289257.head.fastq
-rw-rw-r-- 1 jflucier jflucier 8.5G Mar 18 09:18 GSM1289257.lane.clean
-rw-rw-r-- 1 jflucier jflucier    0 Mar 18 08:57 GSM1289257.lint
-rw-rw-r-- 1 jflucier jflucier  389 Mar 19 10:48 GSM1289257.readlengths.tsv
-rw-rw-r-- 1 jflucier jflucier  222 Mar 19 14:25 GSM1289257.reads.tsv

Please note that I took the fastq generated FastqFilter step even if it produced the Rserver error (#39 )

But If I understood well the code from that filtering step, this is only to produce stats from the filtering step using R. I dont think this bug affect fastq content.

It as been a while I havent written java code.... 

Thanks again for your help.

**Comment by florianerhard** [comment]
Dear jflucier,

wow, that's a stupid bug in the Csv reader class. It tries to interpret your filenames not as strings (as it should), but as genomic regions (that's strings that look like `1-130`). Look at your filenames, that's how they start... there was a check missing whether there is more in the string than the x-y...

This will be fixed in the next release, for now, could you just rename these files (put a letter in front, or remove these numbers).

Florian

**Comment by jflucier** [comment]
this solution worked well

thank you, JF
