### ISSUE TITLE
Mismatch characters in mapping file are not consistent with genome

### ISSUE THREAD

**Issue by aleighbrown** [erhard-lab/gedi#49]
Hello again, 

Some of our newest samples are returning the following errors, although the specific region seems to vary by the sample:

```
Caused by: java.lang.RuntimeException: Mismatch characters in mapping file are not consistent with genome: Genome=TATACATATACATATATACATGTATATATGTATACATATA M4CTr
18+:70342188-70342228	[1] x6 0|40|0	M4CT	M4CTr	M6TC	M6TCr	M33AG	M33AGr	M34CT	M34CTr
```

Attaching a sam of the error region here. 

Any advice appreciated
[error_region.sam.zip](https://github.com/erhard-lab/gedi/files/4944538/error_region.sam.zip)

**Comment by florianerhard** [comment]
Dear Anna-Leigh,

I tested it, it runs just fine here (against the human ensembl v90)!

Best,
Florian

**Comment by aleighbrown** [comment]
Hey Florian, 

Any idea what it's giving this particular error on the entire bam file then? I just did a cut of 18+:70342188-70342228	

The error is pretty esoteric to my eyes. The batch on this sample runs fine for 20/23 samples but is giving similar error for 3 of the files

**Comment by florianerhard** [comment]
This error can only occur, if the genome sequence used for mapping is different to the genome sequence you use for running grandslam. Are you sure that you are using the same assembly including the same patch version?

Florian

**Comment by aleighbrown** [comment]
Hi Florian,

Yep pretty sure, especially given that the other 20 samples ran okay....

**Comment by aleighbrown** [comment]
But for funsies, I will reindex GS and rerun onto the new index to triple
check. I'm also using Gencode GTF as referenced from my previous issue

**Comment by aleighbrown** [comment]
Error persists
```

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@5cd06635
Could not run gedi.slam.javapipeline.SlamCollectStatistics@5cd06635
Exception in parallel iterator thread!
Mismatch characters in mapping file are not consistent with genome: Genome=TACATATATATGTGTGTGTGTGTATATATATACACACACACACATATATATGTA M0TCr
2-:77251157-77251211	[1] x4 0|54|0	M0TC	M0TCr	M2CA	M2CAr	M51GT	M51GTr	M53AG	M53AGr
```

**Comment by aleighbrown** [comment]
Using Gencode v34 with GRCh38.primary_assembly.genome.fa, available here

ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/GRCh38.primary_assembly.genome.fa.gz, 

The only difference being that the gtf is slightly altered:

```
sed -i 's/transcript_type/transcript_biotype/g' gencode_new_biotype.v34.annotation.gtf
sed -i 's/gene_type/gene_biotype/g' gencode_new_biotype.v34.annotation.gtf
```

**Comment by aleighbrown** [comment]
Hi, any clues what may be causing this? I'm happy to share one of the error causing bams

**Comment by florianerhard** [comment]
To be honest, I have no clue what is going on here. I really would like to help, and for that I need to reproduce that. So it would be great if you could share a (as small as possible) bam file, where you get the error. (also: the original gtf is also from gencode 34, right?)

**Comment by aleighbrown** [comment]
Hi Florian, 

You can download a subset of chr18 on this bam from here, this part alone gives the same error

https://liveuclac-my.sharepoint.com/:u:/g/personal/skgta12_ucl_ac_uk/EWLduo0wIXZFnpeo1NrcL28BlVKBd8kDW6wmRS9LxYrYnQ?e=1xFpbX

**Comment by aleighbrown** [comment]
for what it's worth cutting out the error causing segment with
`bedtools intersect -abam Ctrl_2_1h.Aligned.sorted.out.bam -b filter.bed -v > Ctrl_2_1h.Aligned.sorted.out.filtered.bam`
has allowed it to continue running

**Comment by florianerhard** [comment]
Dear Anna-Leigh,

here it ran through just fine... Here's what I did:

```bash
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/GRCh38.primary_assembly.genome.fa.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.primary_assembly.annotation.gtf.gz
gunzip *
sed -i 's/transcript_type/transcript_biotype/g' gencode.v34.primary_assembly.annotation.gtf 
sed -i 's/gene_type/gene_biotype/g' gencode.v34.primary_assembly.annotation.gtf 
gedi -e IndexGenome -s GRCh38.primary_assembly.genome.fa -a gencode.v34.primary_assembly.annotation.gtf -o g34.oml -nomapping -p
gedi -e Slam -prefix slam -genomic g34.oml -reads chr18_Ctrl_2_1h.Aligned.sorted.out.bam -nthreads 6 -plot -D -progress
```

What is the grand-slam version that you run?

Florian

**Comment by aleighbrown** [comment]
Hi Flroian, 

It's version GRAND-SLAM_2.0.5g-pr…iew.zip, we received it on January 29th, 2019

It may be an older version

`gedi -e IndexGenome -s GRCh38.primary_assembly.genome.fa -a gencode.v34.primary_assembly.annotation.gtf -o g34.oml -nomapping -p

An error occurred: Unknown parameter: -nomapping

IndexGenome <Options>

Options:
 -s <fasta-file>		Fasta file containing chromosomes
 -a <gtf-file>		Gtf file containing annotation
 -organism <name>		Organism name to download data from ensembl (e.g. homo_sapiens)
 -version <version>		Ensembl version to download (e.g. 75)
 -gb <genbank-file>		Genbank file containing annotation and sequence
 -gblabel <label>		Which genbank entry to take as gene and transcript label (default: label)
 -gbname <label>		Which genbank entry to take as gene name in the mapping table (default: same as gblabel)
 -gbfeatures <names>		Include other features as ncRNAs (comma separated, default: empty)
 -f <folder>		Output folder (Default: next to Fasta and Gtf / genbank)
 -n <name>		Name of the genome for later use (Default: file name of gtf/genbank-file)
 -o <file>		Specify output file (Default: ~/.gedi/genomic/${name}.oml)
 -nokallisto			Do not create kallisto indices
 -nobowtie			Do not create bowtie indices
 -nostar			Do not create STAR indices
 -nbases <nbases>			Specify nbases parameter for STAR (instead of using the formula in the STAR manual)
 -p			Show progress
 -h			Show this message
 -D			Output debugging information`

**Comment by florianerhard** [comment]
Yes. `-nomapping` is just a shortcut for `-nokallisto -nobowtie -nostar`

However, I am not aware of any change in grandslam that could have changed this behavior... I would ask you nevertheless to download the most recent version and retry!

Best,
Florian

**Comment by aleighbrown** [comment]
Hi Florian, I sent you an email, may have gone to spam, is the correct way to download Grandslam still via contacting you and getting a DropBox link?

Cheers!

**Comment by aleighbrown** [comment]
Hi Florian, 

Any update here? 

Cheers, 
AL
