### ISSUE TITLE
Cannot download PRICE, releases tab link doesn't work

### ISSUE THREAD

**Issue by danielrebib** [erhard-lab/gedi#5]
Hi,

I am trying to download and use this tool. However, the releases tab results in a 404 error and I cannot find another link. Does this tool no longer work?

"Follow these steps to prepare your system for running PRICE:

Download PRICE by choosing the current version from the [releases tab](https://github.com/florianerhard/gedi/releases) and unpack it into any folder (e.g. /home/erhard/Programs/PRICE_1.0.1)"

**Comment by florianerhard** [comment]
Sorry, the link was not up-to-date. Price is part of gedi, so just install [gedi](https://github.com/erhard-lab/gedi?tab=readme-ov-file#installing-gedi)
