### ISSUE TITLE
"location" or "candidate location"

### ISSUE THREAD

**Issue by freeedog** [erhard-lab/gedi#55]
Dose the filtered ORFs can only be obtained as bed file from the orfs.cit file? 
But, the locations in the output bed file is the "candidate location". 
So, should I use the "candidate location" without start codon prediction? 

If I want to the the filtered and start codon predicted ORF, I must viewCIT and find the output ORF in the orf.tsv file.

Is there any way to get the FDR of every ORF?

**Comment by florianerhard** [comment]
Dear Freeedog,

the ${prefix}.orfs.tsv file contains all ORFs without FDR filtering. You can use the p value column for filtering (you need to do the Benjamini-Hochberg correction to obtain the same filtering as in the orfs.cit file).

Do I understand you correctly that you want to get a bed file containing the filtered ORFs? There are many ways to do that, this is one (extracting it from the cit file):

```bash
gedi Nashorn -e 'load("XYZ.orfs.cit").ei().map(function(o) new BedEntry(o.data.getStartStop(o,true).toMutable().setData(new NameAnnotation(o.data.getTranscript()+"_"+o.data.getType()+"_"+o.data.getOrfid())))).print()'
```
Best,
Florian

**Comment by freeedog** [comment]
Thanks for your reply. I got the right output.

**Comment by freeedog** [comment]
Got it. Thank you very much.
