### ISSUE TITLE
buildworkspace.sh build

### ISSUE THREAD

**Issue by jflucier** [erhard-lab/gedi#6]
just a comment in your build file i would include a cp of the gedi executable (on root of git checkout) file. Had to copy it to build folder for gedi to work. Maybe du to my environement.

Just a suggestion. As i said maybe it is my setup.

**Comment by florianerhard** [comment]
Dear jflucier,
thank you for your suggestions. The idea was to let the config dialog that pops up after calling `buildworkspace` write the executable to the folder. But you are right, it does not hurt to also copy it!

Florian
