### ISSUE TITLE
I have not done no4sU sequencing, can I use grand-slam?

### ISSUE THREAD

**Issue by bioinformatica** [erhard-lab/gedi#7]
Hi，

I saw the following on the wiki:

Regression model for the T>C rate in old RNA
Make sure that you either have samples without 4sU to let GRAND-SLAM estimate the regression model from these data, or to have the regression model for you protocol/sequencer. For the former, make sure that the names of the conditions (i.e. given in the metadata of the CIT file, or by the name of the BAM file) include "no4sU" (or, alternatively, use the -no4sUpattern parameter to tell GRAND-SLAM how to identify them). For the latter, specify it via the -errlm parameter.

But I did not do no4sU sequencing. I did 2h, 4h, and 8h treatment groups, and then used 4sU labeling for the same time for the three groups and then performed total RNA sequencing. Can I use grand-slam and grandR for analysis?

**Comment by isaacvock** [comment]
The decimal point part of the gene ID can be removed with a simple call to the base R gsub() function. The generic code to take a data frame with column "gene_id" (this can be changed to whatever you need it to be) and remove this would look like:

```
library(dplyr)

df_fixed <- df %>%
  mutate(gene_id = gsub("\\..*$", "", gene_id))
```

In the context of grandR, you will just need to modify all the relevant tables with this strategy.

Best,
Isaac
