### ISSUE TITLE
Java heap space error + prefix parameter error

### ISSUE THREAD

**Issue by StevenVerbruggen** [erhard-lab/gedi#7]
Dear Florian,

I had some problems running Price. It seems a very useful tool, so I would really like to use it.

First, I built the reference (I see no errors over there, only errors about non-unique genomic regions, can I neglect these?)
`Price_1.0.2/gedi -e IndexGenome -s /data/igenomes/Homo_sapiens/Ensembl/GRCh38/Sequence/WholeGenomeFasta/genome.fa -a /data/igenomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes_86.gtf -n hsa86 -nobowtie -nostar -nokallisto`

Next, I executed Price for two bam files in a bamlist:
`Price_1.0.2/gedi -e Price -reads reads.bamlist -genomic hsa86 -prefix output.hsa86 -percond`
This resulted in a Java heap space error. Following one of the other issues on this side, I updated the last line of the gedi file with `-Xmx16384m`

This seems to help overcome this error, but I got a new one:
```2018-04-10 12:15:10.418 INFO Command: gedi -e Price -reads reads.bamlist -genomic hsa86 -prefix output.hsa86 -percond
2018-04-10 12:15:10.749 INFO Discovering classes in classpath
2018-04-10 12:15:10.919 INFO Preparing simple class references
2018-04-10 12:15:11.055 INFO Gedi 1.0.2 (JAR) startup
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
Could not run program: Mandatory parameters not set: reads genomic prefix

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files
```

Also, in my working directory, there appears a file called `${prefix}.param`. So, I think something is wrong with the prefix argument, although I think it is correctly inputted in the command, right?

Kind regards,
Steven

**Comment by florianerhard** [comment]
Dear Steven,

Could you call it again with `-D` to get a more verbose error message? Also, could you `rm output.hsa96*` any files created by your first run (which crashed due to the memory issue) and try it again?

Best,
Florian

**Comment by StevenVerbruggen** [comment]
Dear Florian,

By running it with `-D`, I got following extra output:
```
java.lang.RuntimeException: Could not run program: Mandatory parameters not set: reads genomic prefix
        at gedi.util.program.GediProgram.run(GediProgram.java:206)
        at executables.Price.main(Price.java:68)
```
I will also run everything again (genome reference build up as well) but directly with the higher memory limit.

Best regards,
Steven

**Comment by StevenVerbruggen** [comment]
Dear Florian?

Does this more verbose error message give you any clue of what could be wrong?
When I execute `Price_1.0.2/gedi -e Price -D -reads reads.bamlist -genomic hsa86 -prefix output.hsa86 -percond`, it seems only the `-D` parameter got parsed into the .param file, the other four arguments does not to go in the program, although I do not see what could be the reason for this. I included the .param as a txt file for your information.
[${prefix}.txt](https://github.com/erhard-lab/gedi/files/1901968/prefix.txt)



Best,
Steven

**Comment by florianerhard** [comment]
Dear Steven,
this is very strange indeed. Could you give me some more information: Which operating system, which java version, which shell do you use?

Best,
Florian

**Comment by StevenVerbruggen** [comment]
Dear Florian,
We have Fedora 23 on our server with Java SE 1.8.0_112. We use Bash shell version 4.3.42

Best,
Steven

**Comment by StevenVerbruggen** [comment]
Dear Florian,

I did some more tests on the mandatory parameters parsing error. We update our java version from 1.8 to version 10.0.1 and Java SE Runtime Environment to 18.3 build 10.0.1. This did not help to overcome the errors.
I looked into the gedi bash script and executed the java jar execute command literally on command line and the same errors pop up. So I guess that the problem is really situated inside the Java code and not in the bash wrapper. Could you maybe make a test version of Price with some test print statements in the parameter parsing parts? Or do you have a better idea to track down this error?

Best regards,
Steven

**Comment by florianerhard** [comment]
Dear Steven,

as I have no other idea where this comes from, and I see no other way how to narrow down this problem (as I cannot reproduce it), let's try this print statement idea.

So, please, replace your `gedi.jar` with this, run it again and post the complete output:
[gedi.zip](https://github.com/erhard-lab/gedi/files/1924603/gedi.zip)

Best,
Florian

**Comment by StevenVerbruggen** [comment]
Dear Florian,

I managed to find the error causing this problem. Apparently there was a typo in one of the paths in the bamlist file. Typo correction fixed both the mandatory parameter as the heap space errors at once! Maybe it is a good idea to build in some extra control on the input data in your pipeline, to track down such errors in the future more quickly. Just a suggestion of course. But anyway, lots of thanks for helping me track down this error.

I got 17 461 ORFs in my output, although there are still some warnings and error messages in my log (see txt attachment `nohup_price_log.txt`)
[nohup_price_log.txt](https://github.com/erhard-lab/gedi/files/1928738/nohup_price_log.txt)
, concerning unreachable array indices. Should I worry about them or do you have an immediate idea of a possible cause of these errors?

In any case, thanky you already for all the help and answers. That really helped!
Best regards,
Steven

**Comment by florianerhard** [comment]
Dear Steven,

you should not ignore these errors. They indicate a parallelization issue with the smile library that we use for start codon prediction by logistic regression. I guess after such errors the predicted start codons will be quite odd... could you try to start with  `gedi -Dsmile.threads=1 -e Price` (after deleting/moving the old output files)?
Best,
Florian

**Comment by StevenVerbruggen** [comment]
Hi Florian,

I executed `Price_1.0.2/gedi -Dsmile.threads=1 -e Price -reads reads.bamlist -genomic hsa_86 -prefix /data2/steven/proteoformer/HCT116/uniq/price/test_1core/output -nthreads 16 -percond`.
This resulted in the following output messages in attachment ([test_smile1.txt](https://github.com/erhard-lab/gedi/files/1937175/test_smile1.txt)). It seems the error messages are gone but the warning messages are still present. Are these a problem? It resulted in 17 430 predicted ORFs.

I executed the same commando (all parameters the same) a second time, and this resulted in 17 359 predicted ORFs. Is there a component in Price which explains this non-replicability?

Best regards,
Steven

**Comment by florianerhard** [comment]
Dear Steven,
the warnings are not a problem. I have no idea why smile has a problem with multithreading in some cases but works just fine in other cases... but as this should not impact on performance, I think I will make this the default in the next release.

Regarding the non-replicability: The inference of the codon model is based on miximizing a non-concave likelihood function, with potentially many local maxima. Price runs the EM algorithm by default for 100000 random starting points (can be specified using `-repeats <N>`). ORFs found in one run and missing in the other should be just below or above the threshold. Anyways, if you end up with differing numbers of ORFs, I would inspect the models (generated if you used `-plot` as png files whether they differ substantially, and visually compare the ORFs using the viewer (you can easily load two output sets using `-a`).

Best,
Florian

**Comment by StevenVerbruggen** [comment]
Dear Florian,
Models look almost completely identical between the two runs. Furthermore, I wrote a little piece of code to check whether the two ORF results files consist of different ORFs. Around 95% of the ORFs were present in both files, so I suppose your statement about ORFs just below or above the threshold is correct.
Thank you very much for the help in solving these errors and questions!
Best regards,
Steven
