### ISSUE TITLE
SEVERE Could not load startup FxStartup.class in /home/gedi.jar

### ISSUE THREAD

**Issue by cz0430** [erhard-lab/gedi#72]
Dear Team,

When I ran gedi to convert bam to CIT, I used the command "/home/gedi -e Bam2CIT -p control.cit control.bam, it generated a message "SEVERE Could not load startup FxStartup.class in /public/home/caizhao/GRAND-SLAM_2.0.5f/gedi.jar". What does this mean?I still got the cit file but I am not sure if this error could affect the output. Is there any way to fix it?Thanks！

Best,
CZ

**Comment by florianerhard** [comment]
Dear CZ,

if you don't have the openfx package installed on your system, this message will appear. However, Fx actually is not used by GRAND-SLAM, and you can safely ignore this message!

Florian
