### ISSUE TITLE
Extract p_c parameter from output

### ISSUE THREAD

**Issue by RPdavies** [erhard-lab/gedi#75]
Hi, Is it possible to extract the estimated $p_c$ parameter (Section 3.3 in your publication: https://doi.org/10.1093/bioinformatics/bty256) from the GRAND-SLAM output?

I expect it will be different between runs, and need them for downstream analysis.

**Comment by florianerhard** [comment]
Dear RPdavies,
graphically, it's in the .single_new.png / double_new.png files (see the [wiki](https://github.com/erhard-lab/gedi/wiki/GRAND-SLAM#other-output-files)), and the values are in rates.tsv in the output folder. Double are the parameters for overlapping parts of paired-end reads. If you do not have paired end data, forget about that.
Best,
Florian

**Comment by RPdavies** [comment]
Thank you very much for your reply! Kind regards
