### ISSUE TITLE
GRAND-SLAM classpath issue

### ISSUE THREAD

**Issue by shino-mrkm** [erhard-lab/gedi#82]
Hi Florian and the team,

I'm trying to use GRAND-SLAM. It looks like a really food tool. However, I'm getting the following error: 

> /home/shino/.local/bin/GRAND-SLAM_2.0.7a/gedi: line 36: gedi_ccp: command not found
> Error: Could not find or load main class executables.IndexGenome
> Caused by: java.lang.ClassNotFoundException: executables.IndexGenome

Following is the command:

> ~/.local/bin/GRAND-SLAM_2.0.7a/gedi -e IndexGenome \
> -s mm10.fa
> -a mm10.refGene.gtf \
> -n mm10 \
> -p -nobowtie -nostar -nokallisto

I am getting the same issue, "Caused by: java.lang.ClassNotFoundException", when I run:
> ~/.local/bin/GRAND-SLAM_2.0.7a/gedi -e Slum -h

Maybe this is a silly mistake of mine, but greatly appreciated if you could help me out.

Thank you so much,
Shino

**Comment by florianerhard** [comment]
Dear Shino,
we made a mistake in the last version (2.0.7a) by adding an old start script to this distribution. It might take some days until it's updated on the download site, please contact me via Email!
Best,
Florian
