### ISSUE TITLE
Hi~How can I get the cit file?

### ISSUE THREAD

**Issue by LongYuan0529** [erhard-lab/gedi#9]
I already have bam file, how can I get the cit file?
I have already tried to use gedi -e Bam2CIT, but the error is "SEVERE Could not load startup FxStartup.class in./gedi.jar
Exception in thread "main"java.lang.UnsupportedOperationException:Cannot query SAM text files
at htsjdk.samtools.SAMTextReader.query(SAMTextReader.java:183)"
Thanks a lot!

**Comment by florianerhard** [comment]
Dear LongYuan0529,
as the error message says, it cannot work with sam text files. Please convert to bam first (and you also need to sort and index)!
Best,
Florian
